#!/bin/sh
if ! head -1 "$1" | grep -qE "^\[(feature|fix|ci|chore|docs|test|style|refactor|perf|build|revert)\]:\s+\S+"; then
  echo "Aborting commit. Your commit message is invalid." >&2
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
  echo "Aborting commit. Your commit message is too long." >&2
  exit 1
fi